name: Update Component Count

on:
  push:
    branches:
      - candidate

jobs:
  update-count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout candidate branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Count Components
        id: count
        run: |
          COUNT=$(ls -l packages/core/src/components | grep '^d' | wc -l)
          echo "{ \"components\": $COUNT }" > count.json
          echo "components=$COUNT" >> $GITHUB_OUTPUT

      - name: Check for Changes
        id: git-check
        run: |
          git add count.json
          if git diff --cached --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or Update Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update component count to ${{ steps.count.outputs.components }} [skip ci]"
          branch: "component-count-update"
          title: "📊 Update component count"
          body: |
            Automatically updates the component count to **${{ steps.count.outputs.components }}** components.

            This PR was created by the component-count workflow.
          base: "candidate"
          labels: "automated PR"
          delete-branch: true
