name: Daily Prettier Linting

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.16.0"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build Packages
        shell: bash
        run: yarn build

      - name: Format Code with Prettier
        run: yarn format

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: format code with Prettier [skip ci]"
          title: "chore: format code with Prettier"
          body: |
            This PR applies automatic formatting changes using Prettier to maintain code consistency.
          base: candidate
          branch: prettier-fix
          labels: formatting
          delete-branch: true
