name: Publish NPM Package (main)

on:
  # Manual trigger option
  workflow_dispatch:
    inputs:
      force-publish:
        description: "Force publish even if not from bump PR"
        required: false
        type: boolean
        default: false

  # Trigger on PR merge to main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    # Only run if:
    # 1. PR was merged (not just closed)
    # 2. Has the release:production label OR force-publish is true
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release:production'))
      || (github.event_name == 'workflow_dispatch' && inputs.force-publish)

    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Setup and Build
        uses: ./.github/actions/setup
        with:
          node-version: "18.x"
          install-immutable: "true"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Packages
        run: yarn build

      - name: Discard Uncommitted Changes
        run: git reset --hard HEAD

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if Packages Need Publishing
        id: check_publish
        run: |
          # Check if there are packages that need publishing
          PACKAGES=$(npx lerna changed --json 2>/dev/null || echo "[]")
          if [ "$PACKAGES" = "[]" ]; then
            echo "needs_publish=false" >> $GITHUB_OUTPUT
            echo "No packages need publishing"
          else
            echo "needs_publish=true" >> $GITHUB_OUTPUT
            echo "Packages to publish: $PACKAGES"
          fi

      - name: Publish Packages with Lerna
        if: steps.check_publish.outputs.needs_publish == 'true'
        id: publish
        run: |
          npx lerna publish from-package --yes --dist-tag latest | tee lerna-output.log
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract Version from Lerna Output
        if: steps.check_publish.outputs.needs_publish == 'true'
        id: get_version
        run: |
          PUBLISHED_VERSION=$(grep -oP '(?<=@lf-widgets/core@)[^ ]+' lerna-output.log | head -1 || echo "")
          if [ -n "$PUBLISHED_VERSION" ]; then
            echo "version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version found in lerna output"
            exit 1
          fi

      - name: Create and Push Tag
        if: steps.check_publish.outputs.needs_publish == 'true' && steps.get_version.outputs.version != ''
        run: |
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin --tags

      - name: Create GitHub Release
        if: steps.check_publish.outputs.needs_publish == 'true' && steps.get_version.outputs.version != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          body: |
            Version: `${{ steps.get_version.outputs.version }}`

            Install with:
            ```bash
            npm install @lf-widgets/core@latest
            # or
            npm install @lf-widgets/core@${{ steps.get_version.outputs.version }}
            ```
          prerelease: false
          generate_release_notes: true
